SELECT DISTINCT

/* Champ SAPCODE */
KNVV.ZZPRCTR AS SAPCODE

/* Champ FINAL_SITENAME */
,CEPCT.KTEXT AS FINAL_SITENAME

/*COMPAGNIE CODE*/
,KNVV.VKORG AS SALESORG 

,CEPC.DATAB AS STARTDATE
,CEPC.DATBI AS ENDDATE

-- Champ BusinessModel
,(CASE WHEN SUBSTR(CEPC.KHINR,6,1) = '2' OR SUBSTR(CEPC.KHINR,6,4) = 'COCO' OR SUBSTR(CEPC.KHINR,6,3) = 'ICR' OR SUBSTR(CEPC.KHINR,7,4) = 'COCO' OR SUBSTR(CEPC.KHINR,7,4) = 'CLCO' OR SUBSTR(CEPC.KHINR,6,4) = 'CLCO' THEN 'COCO' 
    ELSE (CASE WHEN SUBSTR(CEPC.KHINR,6,1) = '3' OR SUBSTR(CEPC.KHINR,6,4) = 'CODO' OR SUBSTR(CEPC.KHINR,6,4) = 'CLDO' OR SUBSTR(CEPC.KHINR,7,4) = 'CLDO' THEN 'CODO'
        ELSE (CASE WHEN SUBSTR(CEPC.KHINR,6,1) = '4' OR SUBSTR(CEPC.KHINR,6,4) = 'DODO' THEN 'DODO' 
            ELSE (CASE WHEN SUBSTR(CEPC.KHINR,7,4) in ('0099','SUPP','CLOS', 'CLSD', 'CLOZ', 'clos', 'CL01', 'CLCL', 'CLCC', 'CLCD', 'JUNK') OR SUBSTR(CEPC.KHINR,6,4) in ('CLOS') THEN 'CLOS' 
                ELSE (CASE WHEN SUBSTR(CEPC.KHINR,7,4) in ('FOOD', 'SDLN', 'SHOP') OR SUBSTR(CEPC.KHINR,6,4) in ('FOOD', 'SDLN', 'SHOP') THEN 'STANDALONE' 
                  ELSE (CASE WHEN SUBSTR(CEPC.KHINR,7,4) in ('WHIT') OR SUBSTR(CEPC.KHINR,6,4) in ('WHIT') THEN 'WHITE'
                    ELSE (CASE WHEN SUBSTR(CEPC.KHINR,7,4) in ('WASH') OR SUBSTR(CEPC.KHINR,6,4) in ('WASH') THEN 'WASH'
                      ELSE ('AUTRE') 
                    END )
                  END )
               END)
            END)
        END)
    END)
END) BusinessModel

/* Champ IsActiveSite */
,(CASE WHEN ((SUBSTR(CEPC.KHINR,7,4) in ('2INA', 'INAC')) OR 
    (SUBSTR(CEPC.KHINR,8,3) in ('IN1','INA', 'GTL', 'IN2', 'INAC'))) THEN 'Non'
     ELSE 'Oui' END) IsActiveSite
/*
################# Dans ce requete on force le status is active 'Non' pour les stations CLOS ##################
,(CASE WHEN ((SUBSTR(CEPC.KHINR,7,4) in ('2INA', 'INAC')) OR 
    (SUBSTR(CEPC.KHINR,8,3) in ('IN1','INA', 'GTL', 'IN2', 'INAC'))) THEN 'Non'
    ELSE (CASE WHEN SUBSTR(CEPC.KHINR,7,4) in ('0099','SUPP','CLOS', 'CLSD', 'CLOZ', 'clos', 'CL01', 'CLCL', 'CLCC', 'CLCD', 'JUNK') THEN 'Non'
     ELSE 'Oui' END) END) IsActiveSite
/*

/* Champ IsPROJECT */
,(CASE WHEN ((SUBSTR(CEPC.KHINR,8,3) in ('PJT', 'PRJ')) OR 
    (SUBSTR(CEPC.KHINR,8,3) in ('NDV','DEV'))) THEN 'Oui' ELSE 'Non' END) IsPROJECT

/* Champ KHINR */
,CEPC.KHINR

,KNA1.LOEVM AS DEALERSTATUS


/* Champ ADRESS */
,CAST( KNA1.STRAS AS VARCHAR(100) ) ADDRESS

/* Champ CODEPOSTAL */
,CAST( KNA1.PSTLZ AS VARCHAR(100) ) ZIPCODE

/* Champ STATE */
,CAST( KNA1.REGIO AS VARCHAR(100) ) STATE

/* Champ SiteTown */
,KNA1.ORT01 AS CITY

/* Champ COUNTRYCODE */
,KNA1.LAND1 AS COUNTRYCODE

/*les informations supplementaire de la table des donn�es g�n�rale de client */
,KNA1.KUNNR AS DEALERCODE
,KNA1.Name1 AS DEALERNAME
,KNA1.NAME2 AS DEALERNAME2
,KNA1.KTOKD AS DEALERACCOUNTGROUP
,KNVV.VTWEG AS DISTRIBUTIONCHANNEL
,KNA1.TELF1 AS TEL
,KNA1.TELFX AS FAX
,KNA1.ERDAT AS DEALERCREATIONDATE
,KNA1.KUKLA AS DEALERCLASSICATION
,KNA1.STCD1 AS TAXENUMBER

/* Champ LOADING_DATE */
,CURRENT_DATE AS EXTRACT_DATE



/********* Jointure des tables **********/

FROM 

/** Table KNVV => KNVV **/
SAPC47.KNVV@P2J.WORLD KNVV

JOIN 
/** Table KNVV - Replace the country => T2 **/
    (SELECT ZZPRCTR, max(ERDAT) lastdate FROM SAPC47.KNVV@P2J.WORLD
    WHERE substr(ZZPRCTR,1,2) in ('MA') 
    AND VTWEG LIKE '20' GROUP BY ZZPRCTR) AS T2
ON  KNVV.ZZPRCTR = T2.ZZPRCTR and KNVV.ERDAT = lastdate

JOIN 
    /** Table CEPC => CEPC **/
    (SELECT PRCTR, KHINR, DATAB , MAX(DATBI) AS DATBI FROM SAPC47.CEPC@P2J.WORLD 
    WHERE SUBSTR(PRCTR,6,1) = 'S' 
    GROUP BY PRCTR, KHINR, DATAB) CEPC
ON  CEPC.PRCTR = KNVV.ZZPRCTR

JOIN 
    /** Table KNA1 => KNA1 **/
    SAPC47.KNA1@P2J.WORLD KNA1
ON  KNVV.KUNNR = KNA1.KUNNR

JOIN
    /** Table CEPCT => CEPCT **/
    SAPC47.CEPCT@P2J.WORLD CEPCT
ON  CEPC.PRCTR=  CEPCT.PRCTR 


/********* Condition WHERE **********/

WHERE 
SUBSTR(KNVV.ZZPRCTR,6,1) = 'S'
AND KNVV.VKORG in  ('0819')


/********* ORDER BY **********/

ORDER BY SAPCODE;